version: '3.9'
services:
  pg:
    restart: always
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  postgres_dev:
  cache:
    driver: local
