spring:

  # disable Spring Shell by default
  shell:
    interactive:
      enabled: false
    noninteractive:
      enabled: false
    scripting:
      enabled: false

  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  data:
    redis:
      host: localhost
      jedis:
        pool:
          enabled: true
          max-active: 8
          max-wait: 1s
          min-idle: 0
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-wait: 1s
          min-idle: 0
